name: vitapos
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  connectivity_plus: ^4.0.2
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.0
  http: ^1.1.0
  shared_preferences: ^2.2.1
  shimmer: ^2.0.0
  cached_network_image: ^3.3.0
  blue_thermal_printer: ^1.2.3
  intl: ^0.18.1
  infinite_scroll_pagination: ^4.0.0
  decimal: ^2.3.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
